/** The measured half of this site.
 *
 * `content/progress.json` is generated by `python scripts/cb.py docs-sync`,
 * which reads `scripts/spec.py` (what should be true) and `scripts/status.py`
 * (what the QA repo, the v2 scenario files and an actual test run say is true).
 * Nothing here is hand-maintained: a number typed into a page by a human is a
 * number that is wrong three commits later, and this whole site exists to be
 * trusted at a glance.
 */
import data from '@/content/progress.json';

export type Status = 'done' | 'partial' | 'planned' | 'blocked';

export interface ScenarioCounts {
  spec: number;
  ported: number;
  green: number;
  failing: number;
}

export interface FeatureRow {
  id: string;
  title: string;
  area: string;
  layer: string;
  milestone: string;
  status: Status;
  triggers: string[];
  v1_source: string;
  notes: string;
  contract: string | null;
  scenarios: ScenarioCounts;
  url: string;
}

export interface MilestoneRow {
  id: string;
  title: string;
  done: number;
  total: number;
}

export interface ScenarioLedgerRow {
  stem: string;
  spec: number;
  ported: number;
  green: number;
  failing: number;
  state: string;
}

export interface DefectRow {
  id: string;
  text: string;
  addressed: boolean;
}

export interface Progress {
  generated_at: string;
  commit: string;
  test_summary: string;
  totals: {
    features: number;
    done: number;
    partial: number;
    planned: number;
    blocked: number;
    spec_scenarios: number;
    ported: number;
    spec_files: number;
    spec_files_covered: number;
    new_specs: number;
    green: number;
    failing: number;
  };
  milestones: MilestoneRow[];
  features: FeatureRow[];
  scenarios: ScenarioLedgerRow[];
  defects: DefectRow[];
  problems: string[];
}

export const progress = data as unknown as Progress;

export const statusLabel: Record<Status, string> = {
  done: 'Done',
  partial: 'Partial',
  planned: 'Planned',
  blocked: 'Blocked',
};

/** One colour vocabulary for the whole site. Every badge, bar and dot reads
 * from this map, so a status can never mean green in one pane and amber in
 * another — the failure that makes a dashboard worse than no dashboard. */
export const statusClass: Record<Status, string> = {
  done: 'bg-cb-success/12 text-cb-success-ink dark:text-cb-success ring-cb-success/25',
  partial: 'bg-cb-warning/14 text-cb-warning-ink dark:text-cb-warning ring-cb-warning/30',
  planned: 'bg-fd-muted text-fd-muted-foreground ring-fd-border',
  blocked: 'bg-cb-error/12 text-cb-error-ink dark:text-cb-error ring-cb-error/25',
};

export const statusBar: Record<Status, string> = {
  done: 'bg-cb-success',
  partial: 'bg-cb-warning',
  planned: 'bg-fd-muted-foreground/25',
  blocked: 'bg-cb-error',
};

export function featuresByArea(): Record<string, FeatureRow[]> {
  const out: Record<string, FeatureRow[]> = {};
  for (const feature of progress.features) (out[feature.area] ??= []).push(feature);
  return out;
}

export function featureById(id: string): FeatureRow | undefined {
  return progress.features.find((feature) => feature.id === id);
}

export function percent(done: number, total: number): number {
  return total === 0 ? 0 : Math.round((done / total) * 100);
}
