"""`cb_worker.distort` on real bytes — no bot, no queue, no network.

Seam carving is the one part of x_distortion that is not a straight port of a
v1 call: v1 reached ImageMagick's `liquid_rescale` through `wand`, and this is
the same algorithm over numpy (module docstring). So these assert the
properties that matter — the output is a valid image of the *original* size,
the carve really removes the requested number of seams, and a degenerate input
does not raise where v1 would not have.

The audio arm shells out to ffmpeg, which is the outside world and is present
in the cb-worker image (`Dockerfile:203`); its test skips cleanly when the
binary is not on PATH, the same rule the integration layer uses for Postgres.
"""

from __future__ import annotations

import io
import shutil
import subprocess

import numpy as np
import pytest
from PIL import Image

from cb_worker.distort import (
    DEFAULT_DISTORT_PERCENT,
    MAX_CARVE_DIMENSION,
    distort_audio_bytes,
    distort_image,
    seam_carve,
)


def _sample(width: int = 160, height: int = 120) -> Image.Image:
    """A picture with real structure, so the energy function has something to
    prefer — a flat fill would make every seam equivalent and prove nothing."""
    return Image.effect_mandelbrot((width, height), (-2.0, -1.5, 1.0, 1.5), 60).convert("RGB")


def _png(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


# ---------------------------------------------------------------- seam carving


def test_carving_removes_exactly_the_requested_seams() -> None:
    carved = seam_carve(_sample(100, 80), 25)
    assert carved.size == (25, 20)


def test_carving_is_not_a_plain_resize() -> None:
    """A content-aware carve and a uniform resize of the same picture to the
    same size must not agree — if they did, the energy pass is doing nothing."""
    original = _sample(80, 64)
    carved = np.asarray(seam_carve(original, 50), dtype=np.int16)
    resized = np.asarray(original.resize(carved.shape[1::-1]), dtype=np.int16)
    assert np.abs(carved - resized).mean() > 1.0


def test_a_one_pixel_image_does_not_raise() -> None:
    """`int(1 * 0.25)` is 0, and a zero-width image is not an image. v1 would
    have handed ImageMagick the same 0 — clamped here rather than discovered
    in production."""
    assert seam_carve(Image.new("RGB", (1, 1), "white"), DEFAULT_DISTORT_PERCENT).size == (1, 1)


# ------------------------------------------------------------- the image arm


@pytest.mark.parametrize("fmt", ["PNG", "JPEG"])
def test_distorted_image_keeps_the_original_size(fmt: str) -> None:
    """v1 resizes back to the original after carving (`Distortioner.py:43`),
    so a `/destroy` never changes the picture's dimensions."""
    original = _sample(200, 150)
    out = distort_image(_png(original), fmt=fmt)
    with Image.open(io.BytesIO(out)) as result:
        assert result.size == original.size
        assert result.format == fmt


def test_distortion_actually_changes_the_pixels() -> None:
    original = _sample(120, 96)
    out = distort_image(_png(original), fmt="PNG")
    with Image.open(io.BytesIO(out)) as result:
        changed = np.abs(
            np.asarray(result.convert("RGB"), dtype=np.int16) - np.asarray(original, dtype=np.int16)
        )
    assert changed.mean() > 1.0


def test_a_large_image_is_carved_at_a_bounded_size() -> None:
    """The carve cost is quadratic in the working size, so it runs on a
    thumbnail and the result is scaled back up (module docstring). This asserts
    the bound is real rather than aspirational: a 1280px photo still returns at
    1280px, which only the upscale path can produce."""
    original = _sample(1280, 720)
    out = distort_image(_png(original), fmt="JPEG")
    with Image.open(io.BytesIO(out)) as result:
        assert result.size == (1280, 720)
    assert MAX_CARVE_DIMENSION < 1280


def test_a_transparent_png_is_accepted() -> None:
    """Stickers arrive as RGBA; `Image.open` alone would leave a 4-channel
    array the carve's `mean(axis=2)` silently mis-weights."""
    sticker = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    sticker.paste(_sample(32, 32), (16, 16))
    out = distort_image(_png(sticker), fmt="PNG")
    with Image.open(io.BytesIO(out)) as result:
        assert result.size == (64, 64)


# -------------------------------------------------------------- the audio arm


def _has_ffmpeg() -> bool:
    return shutil.which("ffmpeg") is not None


def _one_second_of_sine() -> bytes:
    """A real ogg, generated by ffmpeg itself rather than checked in.

    Synchronous on purpose: `subprocess.run` inside an `async def` is
    ASYNC221, and this is fixture-shaped setup, not the thing under test.
    """
    return subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-f",
            "ogg",
            "-",
        ],
        check=True,
        capture_output=True,
    ).stdout


@pytest.mark.skipif(not _has_ffmpeg(), reason="ffmpeg is not on PATH")
async def test_audio_is_vibratoed_into_an_mp3() -> None:
    out = await distort_audio_bytes(_one_second_of_sine(), suffix=".ogg")
    assert out, "ffmpeg produced no output"
    # ID3 tag or a bare MPEG frame sync — either is a real mp3.
    assert out[:3] == b"ID3" or out[0] == 0xFF


@pytest.mark.skipif(not _has_ffmpeg(), reason="ffmpeg is not on PATH")
async def test_a_file_ffmpeg_cannot_read_raises_rather_than_returning_junk() -> None:
    """The job catches this and answers `destroy.instru`; v1 printed the
    exception and left the user with nothing (`Distortioner.py:160-161`)."""
    with pytest.raises(subprocess.CalledProcessError):
        await distort_audio_bytes(b"not audio at all", suffix=".ogg")
