"""The published OpenAPI document, as something a test can assert against.

`docs/site/public/openapi.json` is generated by `scripts/api_spec.py` and
committed. `test_contract.py` validates every response the API gives against
the schema in *that file* — not against the document the app would build right
now, which would be circular: an app validated against its own live description
agrees with itself by construction and can change shape freely.

The check that keeps the file honest is `api-docs --check` in `cb.py check`. So
the loop is: change a response model, regenerate, the diff shows what clients
will see, and the contract tests validate against the reviewed artifact.

## Why `jsonschema-rs`

It is the Rust implementation, with Python bindings — a schema is compiled once
into a validator and then reused across hundreds of payloads, which is the exact
shape of this suite. It is also the same trade the rest of this repository
already makes (ruff, uv, granian, msgspec).

## `$ref`, and why the whole document is handed to the validator

Every response schema is a `$ref` into `components/schemas`, and those refer to
each other. Rather than inlining, each validator is built from the *entire*
document with `$ref: "#/components/schemas/X"` as its root, so the resolver has
everything it needs and nested models are checked to the leaves.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

import jsonschema_rs

ROOT = Path(__file__).resolve().parents[2]
SPEC_FILE = ROOT / "docs" / "site" / "public" / "openapi.json"


@lru_cache(maxsize=1)
def spec() -> dict[str, Any]:
    return dict(json.loads(SPEC_FILE.read_text()))


def operation(method: str, path: str) -> dict[str, Any] | None:
    """The document's entry for one operation, or `None` if it has none."""
    return spec().get("paths", {}).get(path, {}).get(method.lower())


def response_schema(method: str, path: str, status: int) -> dict[str, Any] | None:
    """The declared JSON schema for one status, or `None` when the document
    declares that status without a body model.

    `None` is a real answer, not a failure: several refusals are declared with a
    description and no model, and a test that treated that as an error would be
    asserting something the document never promised.
    """
    op = operation(method, path)
    if op is None:
        return None
    response = (op.get("responses") or {}).get(str(status))
    if not response:
        return None
    content = (response.get("content") or {}).get("application/json")
    schema = (content or {}).get("schema")
    return schema if isinstance(schema, dict) and schema else None


@lru_cache(maxsize=256)
def _validator(pointer: str) -> jsonschema_rs.Validator:
    document = dict(spec())
    document["$ref"] = pointer
    return jsonschema_rs.validator_for(document)


def errors_against(schema: dict[str, Any], payload: Any) -> list[str]:
    """Every way `payload` fails `schema`, as readable strings.

    All of them, not the first: a response that drifted usually drifted in more
    than one field, and a test that reports one per run costs one run per field.
    """
    pointer = schema.get("$ref")
    if pointer is None:
        # An inline schema (a handful of endpoints declare one) — validate it as
        # given, still resolved against the whole document.
        document = dict(spec())
        document.update(schema)
        validator = jsonschema_rs.validator_for(document)
    else:
        validator = _validator(pointer)
    return [
        f"{'/'.join(str(p) for p in error.instance_path) or '<root>'}: {error.message}"
        for error in validator.iter_errors(payload)
    ]


def paths_with_schema() -> list[tuple[str, str]]:
    """Every `(method, path)` the document describes, for parametrised sweeps."""
    return [
        (method, path) for path, methods in spec().get("paths", {}).items() for method in methods
    ]


__all__ = [
    "SPEC_FILE",
    "errors_against",
    "operation",
    "paths_with_schema",
    "response_schema",
    "spec",
]
