"""fun_meme's template catalog — v1's `meme_metadata.csv`, as a frozen index.

v1 built this dict at import time from a CSV next to the images
(`../COOKIEBOT-Telegram-Group-Bot/Bot/SocialContent.py:35-47`), keyed
`language -> blob_count -> [template]`, where a "blob" is a green rectangle in
the template that a member's profile picture gets pasted over. The CSV itself
is generated by `Bot/Static/Meme/metadata.py`, which finds those rectangles
with OpenCV's `inRange((0,210,0),(40,255,40))` + `findContours` — offline, once
per template, never at request time.

**The CSV is ported verbatim as package data; the images are not.** 802 rows
of metadata is 97 kB; the templates they describe are 110 MB across 801 files,
which is far past what belongs in a wheel (`fun_meme.mdx` already recorded
that sizing as this feature's own decision). The images live in
`cb_core.storage.store()` under `meme/templates/<Language>/<filename>`, put
there once by `python scripts/cb.py meme-seed` — the same split
`platform_bucket_export` makes for v1's GCS assets, and the reason
`cb_core.assets` (package data, `fun_complaint`'s 3.4 MB) is not used here.

Verbatim with exactly one deletion, and it is not a style choice: v1 deleted
`Portuguese/photo_1893@29-11-2019_02-34-09.jpg` (commit `cf87b052`) without
regenerating the CSV, so its row described bytes that no longer existed
anywhere. v1 could survive that — it read the image at request time and threw —
but v2 seeds from this catalog, so the row meant `meme-seed` reported a failure
on every run and `/meme` could still draw a template it was then unable to
render. The row is gone; the two images v1 added *without* regenerating the CSV
(`ebp6ryoge6t91.webp`, `photo_654@09-07-2019_17-14-13.jpg`) stay out of the
catalog, because v1 never offered them either.

This module is in `cb-core` rather than `cb-worker` because both the seeder and
the job have to agree on the storage key, and a key computed in two places is a
key that eventually differs.
"""

from __future__ import annotations

import ast
import csv
import random
from importlib import resources
from types import MappingProxyType

import msgspec

#: v1's own two directory names, and the values in the CSV's `language` column.
ENGLISH = "English"
PORTUGUESE = "Portuguese"

#: Where a template's bytes live. Not content-addressed (unlike
#: `media_objects`): a template is identified by the name v1 gave it, the CSV
#: refers to it by that name, and re-seeding must overwrite rather than
#: accumulate.
KEY_PREFIX = "meme/templates"

#: v1 searches upward from the number of tagged members to this bound
#: (`SocialContent.py:236`), i.e. blob counts 1..5. `metadata.py:8` caps
#: generation at the same number.
MAX_BLOBS = 5

_DATA_PACKAGE = "cb_core.asset_data.meme"
_CSV_NAME = "meme_metadata.csv"


class MemeTemplate(msgspec.Struct, frozen=True):
    """One row of v1's CSV.

    `blob_rects` are `(x, y, w, h)` in template pixel coordinates, already
    reduced from contours by `metadata.py:get_rects` — v1's runtime re-derives
    nothing, and neither does this.
    """

    filename: str
    language: str
    blob_count: int
    blob_rects: tuple[tuple[int, int, int, int], ...]

    @property
    def storage_key(self) -> str:
        return f"{KEY_PREFIX}/{self.language}/{self.filename}"


def _load() -> dict[str, dict[int, tuple[MemeTemplate, ...]]]:
    """`language -> blob_count -> templates`, v1's exact shape (`:43-47`).

    Rows with `blob_count == 0` are kept out: a template with no green
    rectangle has nowhere to paste a face, and v1's own selection loop starts
    at `len(members_tagged)`, which is never negative — so it could never
    choose one either.
    """
    index: dict[str, dict[int, list[MemeTemplate]]] = {}
    raw = resources.files(_DATA_PACKAGE).joinpath(_CSV_NAME).read_text(encoding="utf-8")
    for row in csv.DictReader(raw.splitlines()):
        blob_count = int(row["blob_count"])
        if blob_count <= 0:
            continue
        rects = ast.literal_eval(row["blob_rects"]) if row["blob_rects"] else []
        template = MemeTemplate(
            filename=row["filename"],
            language=row["language"],
            blob_count=blob_count,
            blob_rects=tuple(tuple(int(v) for v in rect) for rect in rects),  # type: ignore[misc]
        )
        index.setdefault(template.language, {}).setdefault(blob_count, []).append(template)
    return {
        language: {count: tuple(items) for count, items in sorted(by_count.items())}
        for language, by_count in index.items()
    }


_INDEX = MappingProxyType(_load())


def metadata_language(lang: str) -> str:
    """v1: `'Portuguese' if 'pt' in language.lower() else 'English'`
    (`SocialContent.py:234`).

    Note what that does to a Spanish group: `'pt' not in 'es'`, so it gets the
    English templates. Preserved — the alternative is inventing a pool that
    does not exist.
    """
    return PORTUGUESE if "pt" in lang.lower() else ENGLISH


def suitable(tagged_count: int, lang: str) -> tuple[MemeTemplate, ...]:
    """Every template that can seat at least `tagged_count` people.

    v1's own widening loop (`:236-243`): take blob counts from the number of
    tagged members up to `MAX_BLOBS`, and — **only for Portuguese** — fall back
    to the English pool when that yields nothing. There is no reverse fallback:
    an English group is never shown a Portuguese template, because the caption
    text is baked into the image.
    """
    language = metadata_language(lang)
    picked = _collect(language, tagged_count)
    if not picked and language == PORTUGUESE:
        picked = _collect(ENGLISH, tagged_count)
    return picked


def _collect(language: str, tagged_count: int) -> tuple[MemeTemplate, ...]:
    by_count = _INDEX.get(language, {})
    out: list[MemeTemplate] = []
    for count in range(max(tagged_count, 1), MAX_BLOBS + 1):
        out.extend(by_count.get(count, ()))
    return tuple(out)


def choose(tagged_count: int, lang: str, rng: random.Random | None = None) -> MemeTemplate | None:
    """One template at random from `suitable`, or `None` when there are none.

    v1 has no `None` branch: `contours_green` is only assigned inside
    `if suitable_templates:` and is read unconditionally straight afterwards
    (`:244-248`), so an empty pool is a `NameError` that kills the update with
    no reply — D-ME-1 in `docs/contracts/fun_meme.md`.
    """
    pool = suitable(tagged_count, lang)
    if not pool:
        return None
    picker = rng.choice if rng is not None else random.choice
    return picker(list(pool))


def all_templates() -> tuple[MemeTemplate, ...]:
    """Every template in the catalog — what the seeder iterates."""
    return tuple(
        template
        for by_count in _INDEX.values()
        for templates in by_count.values()
        for template in templates
    )


__all__ = [
    "ENGLISH",
    "KEY_PREFIX",
    "MAX_BLOBS",
    "PORTUGUESE",
    "MemeTemplate",
    "all_templates",
    "choose",
    "metadata_language",
    "suitable",
]
